// autogenerated: do not edit!
// generated from gentemplate [./gentemplate -d Package=netlink -id Attr -d VecType=AttrVec -d Type=Attr github.com/platinasystems/elib/vec.tmpl]

package netlink

import (
	"github.com/platinasystems/elib"
)

type AttrVec []Attr

func (p *AttrVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Attr, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *AttrVec) validate(i uint, zero *Attr) *Attr {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]Attr, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *AttrVec) Validate(i uint) *Attr                { return p.validate(i, (*Attr)(nil)) }
func (p *AttrVec) ValidateInit(i uint, zero Attr) *Attr { return p.validate(i, &zero) }

func (p AttrVec) Len() uint { return uint(len(p)) }
